/**
 * @xinuco/types — Tipos compartidos de la plataforma Xinuco.
 * Incluye: Database, Business, UserRole, BusinessFeatures, etc.
 */
export type {
  Json,
  Database,
  Business,
  BusinessInsert,
  BusinessFeatures,
  BrandConfig,
  Profile,
  UserRole,
  Service,
  ServiceAudience,
  ServiceAudienceOrAll,
  Staff,
  StaffRole,
  StaffSchedule,
  StaffBreak,
  StaffTimeOff,
  StaffTimeOffKind,
  Appointment,
  AppointmentStatus,
  Customer,
  SaleItem,
  CommissionRule,
  LedgerEntryType,
  TeamPaymentMethod,
  StaffLedgerEntry,
  StaffLedgerBalance,
  Expense,
  ExpenseCategory,
  ExpenseCategoryRow,
  ExpensePaymentMethod,
  ProfitLossResult,
  ProfitLossCategoryEntry,
  MoneyMovement,
  StaffProduction,
  MoneyMovementKind,
  MoneyMovementSource,
  MoneyMovementMethod,
  PaymentMethod,
  CashRegisterShift,
  Sale,
  Payment,
  InventoryItem,
  InventoryCategory,
  InventoryMovement,
  InventoryMovementResult,
  MovementType,
  AuditLog,
  AuditCategory,
  FixedAsset,
  FixedAssetCategory,
  DepreciationMethod,
  DepreciationSchedule,
  AssetPortfolioSummary,
  AssetPaymentMethod,
  DisposalReason,
} from './database'

export type { Database as DatabaseGenerated } from './database.types'
